name : CI

on : 
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses : actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
         java-version: '17'
         distribution: 'temurin'

      - name: permission for gradlew
        run: chmod +x ./gradlew

      - name: test with gradle
        run: ./gradlew test
        shell: bash
